env:
    es6: true
    node: true

parser: '@typescript-eslint/parser'
parserOptions:
    project: tsconfig.json
plugins:
    - '@typescript-eslint'
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'

rules:
    key-spacing:
        - warn
        - align: colon
    indent:
        - error
        - 4
        - { flatTernaryExpressions: true }
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    prefer-destructuring:
        - error
    object-shorthand:
        - error
    '@typescript-eslint/prefer-nullish-coalescing':
        - warn
    '@typescript-eslint/prefer-optional-chain':
        - warn
